name: mir-kiosk-kodi
adopt-info: kodi
summary: Kodi packaged as a mir-kiosk snap
description: Kodi-wayland packaged as a mir-kiosk snap
confinement: strict
grade: stable
base: core20
license: GPL-2.0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
#  - build-on: i386

environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/:/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep Kodi
  WINDOWING: wayland

layout:
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/kodi:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/kodi
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba
  /usr/share/glvnd:
    bind: $SNAP/usr/share/glvnd
  /usr/share/kodi:
    bind: $SNAP/usr/share/kodi
  /usr/share/samba:
    bind: $SNAP/usr/share/samba
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb

plugs:
  wayland:
  opengl:
  audio-playback:
  pulseaudio:
  alsa:
  avahi-observe:
  hardware-observe:
  locale-control:
  mount-observe:
  network-bind:
  network-observe:
  removable-media:
  shutdown:
  system-observe:

apps:
  daemon:
    command: bin/run-daemon wayland-launch $SNAP/usr/bin/kodi
    daemon: simple
    restart-condition: always
    environment:
      # Prep PulseAudio
      PULSE_SYSTEM: 1
      PULSE_RUNTIME_PATH: /var/run/pulse

  mir-kiosk-kodi:
    command: bin/wayland-launch $SNAP/usr/bin/kodi
    desktop: usr/share/applications/kodi.desktop
    environment:
      # Prep PulseAudio
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

parts:
  ppa-setup:
    plugin: nil
    # Use the upstream PPA where possible
    override-pull: |
      if [ "$SNAP_ARCH" = "amd64" ] || [ "$SNAP_ARCH" = "i386" ]; then
        sudo apt --assume-yes install software-properties-common
        sudo add-apt-repository -yu ppa:team-xbmc/ppa
        snapcraftctl pull
      fi

  kodi:
    after: [ ppa-setup ]
    plugin: nil
    override-pull: |
      snapcraftctl pull
      kodi_version=`LANG=C apt-cache policy kodi-wayland | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      snapcraftctl set-version $kodi_version
    stage-packages:
      - kodi
      - kodi-wayland
      - kodi-visualization-spectrum
      - kodi-repository-kodi
      - on amd64: [kodi-inputstream-adaptive] # only available for x86
      - on i386: [kodi-inputstream-adaptive] # only available for x86
      - python
      - samba-libs
      - samba-common-bin
      - samba-common
      - libfstrcmp0
      - libpulse0
      - libaudio2
      - try: [libsndio7.0]  # core20
      - else: [libsndio6.1] # core18
  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - va-driver-all

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh alsa avahi-observe hardware-observe locale-control mount-observe network-observe network-bind removable-media shutdown system-observe wayland
    stage-packages:
      - inotify-tools
