name: mir-kiosk-kodi
adopt-info: kodi
summary: Kodi packaged as a mir-kiosk snap
description: Kodi packaged as a mir-kiosk snap
confinement: strict
grade: stable
base: core22
license: GPL-2.0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
#  - build-on: i386

package-repositories:
  - type: apt
    ppa: team-xbmc/ppa

environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: $SNAP/usr/lib/:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/blas:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/lapack${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  WINDOWING: wayland

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/kodi:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/kodi
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba
  /usr/share/kodi:
    bind: $SNAP/usr/share/kodi
  /usr/share/samba:
    bind: $SNAP/usr/share/samba
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/share/libdrm:  # Needed by mesa-core22-test on AMD GPUs
    bind: $SNAP/graphics/usr/share/libdrm
  /usr/share/drirc.d:  # Used by mesa-core22-test for app specific workarounds
    bind: $SNAP/graphics/usr/share/drirc.d

plugs:
  wayland:
  opengl:
  audio-playback:
  pulseaudio:
  alsa:
  avahi-observe:
  hardware-observe:
  locale-control:
  mount-observe:
  network-bind:
  network-observe:
  removable-media:
  shutdown:
  system-observe:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22/edge

apps:
  daemon:
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
      - bin/graphics-core22-wrapper-kodi
    command: usr/bin/kodi
    daemon: simple
    restart-condition: always
    environment:
      # Prep PulseAudio
      PULSE_SYSTEM: 1
      PULSE_RUNTIME_PATH: /var/run/pulse

  mir-kiosk-kodi:
    command-chain:
      - bin/wayland-launch
      - bin/graphics-core22-wrapper-kodi
    command: usr/bin/kodi
    desktop: usr/share/applications/kodi.desktop
    environment:
      # Prep PulseAudio
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

parts:
  kodi:
    plugin: nil
    override-pull: |
      craftctl default
      kodi_version=`LANG=C apt-cache policy kodi | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      craftctl set version=$kodi_version
    stage-packages:
      - kodi
      - kodi-inputstream-adaptive
      - python3
      - libsndio7.0
      - kodi-visualization-spectrum
      - samba-libs
      - samba-common-bin
      - samba-common
      - libfstrcmp0
      - libpulse0
      - libaudio2

  scripts:
    plugin: dump
    source: scripts
    stage-packages:
      - inotify-tools

  graphics-core22:
    after: [kodi, scripts]
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22
      rm -rf ${CRAFT_PRIME}/{bug,doc,lintian,man}
    prime:
      - bin/graphics-core22-wrapper
